version: '3.8'

services:
  api:
    build: .
    volumes:
      - .:/app
    env_file:
      - clickhouse_api/.env
    environment:
      - USE_CLICKHOUSE=true
      - REDISCLOUD_URL=redis://redis:6379/0
      - REDIS_DO_URL=redis://redis:6379/1
    ports:
      - "127.0.0.1:5012:5000"
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:alpine
    user: "0:0"
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - /mnt/expansion/dockers_drives/redis_data:/data
    command: [ "redis-server", "--appendonly", "yes" ]

# Usando bind mounts en /mnt/expansion/dockers_drives/
